In [1]:
import numpy as np

In [2]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
np.ones(2)

array([1., 1.])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [7]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [8]:
mx_1s.dtype

dtype('float64')

In [11]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
mx_1s=np.ones((3,4),dtype= int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [15]:
mx_0s=np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [16]:
mx_0s=np.zeros((4,6),dtype= bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [17]:
mx_0s=np.zeros((4,6),dtype= str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [18]:
em_st=''
print(bool(em_st))

False


In [19]:
em_mx=np.empty((2,3))
print(em_mx)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [3.33775509e-307 2.67018098e-306 1.11262266e-307]]
