# random sampling with numpy

In [1]:
import numpy as np
import random

In [5]:
np.random.random(1)

array([0.41957124])

In [6]:
np.random.random((3,3))

array([[0.08847872, 0.52091575, 0.77961836],
       [0.46307543, 0.24469496, 0.5965182 ],
       [0.66911747, 0.85073179, 0.14824545]])

In [14]:
np.random.randint(1,4)

2

In [16]:
np.random.randint(1,4,(4,4))

array([[2, 2, 1, 2],
       [2, 1, 1, 1],
       [1, 2, 1, 2],
       [2, 2, 2, 1]])

In [17]:
np.random.randint(1,4,(2,4,4))

array([[[1, 2, 2, 2],
        [3, 1, 1, 3],
        [1, 2, 1, 3],
        [3, 3, 2, 1]],

       [[3, 3, 3, 1],
        [1, 3, 3, 1],
        [3, 3, 3, 3],
        [3, 1, 2, 2]]])

In [19]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [20]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [21]:
2**32-1

4294967295

In [22]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [23]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [24]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [25]:
x=[1,2,3,4]

In [28]:
np.random.choice(x)

1

In [29]:
np.random.choice(x)

2

In [30]:
for i in range(20):
    print(np.random.choice(x))

1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3
4


In [31]:
x

[1, 2, 3, 4]

In [32]:
np.random.permutation(x)

array([2, 3, 4, 1])

In [33]:
np.random.permutation(x)

array([2, 4, 3, 1])

In [34]:
np.random.shuffle(x)